name: Semgrep
on:
  pull_request_target:
    branches:
      - next
      - main
  push:
    branches:
      - next
      - main
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
     - if: github.event_name == 'push'
       run: |
        echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
        echo "REF=${{ github.REF }}" >> $GITHUB_ENV
     - if: github.event_name == 'pull_request_target'
       run: |
        echo "REPOSITORY=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_ENV
        echo "REF=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
     - uses: 'phantomcyber/dev-cicd-tools/github-actions/semgrep@main'
       with:
        SEMGREP_DEPLOYMENT_ID: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        REPOSITORY: ${{ github.repository }}
        REF: ${{ github.ref }}
